# -*- coding: utf-8 -*-
# This file is auto-generated by sync_styles.py and can be executed to regenerate vibe-coding-grade-board.html.

html_content = """<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>동학년 게시판 만들기 | 초록덕후의 교실 도구함</title>
  <style>
    @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');

    @font-face {
      font-family: 'NanumSquareRound';
      font-weight: 400;
      font-style: normal;
      font-display: swap;
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/NanumSquareRoundR.woff2') format('woff2');
    }
    @font-face {
      font-family: 'NanumSquareRound';
      font-weight: 700;
      font-style: normal;
      font-display: swap;
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/NanumSquareRoundB.woff2') format('woff2');
    }

    /* 기존 테마 CSS 변수 연결 */
    :root {
      --green: #15803d;
      --green-deep: #14532d;
      --green-bright: #16a34a;
      --green-soft: #dcfce7;
      --green-mist: #f0fdf4;
      --ink: #17201a;
      --body: #27352b;
      --muted: #66736a;
      --line: #e3e8e1;
      --line-green: #bbf7d0;
      --canvas: #ffffff;
      --warm: #fafaf7;
      --surface: #f6f8f5;
      --dark: #102418;
      --shadow: 0 22px 50px rgba(16, 36, 24, 0.08);
      --radius-lg: 22px;
      --radius-xl: 30px;
      --font-body: 'Pretendard', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', system-ui, sans-serif;
      --font-display: 'NanumSquareRound', 'Pretendard', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', system-ui, sans-serif;
      --max: 800px;
    }

    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: var(--font-body);
      color: var(--body);
      background:
        radial-gradient(circle at 15% 0%, rgba(187, 247, 208, 0.4), transparent 30%),
        linear-gradient(180deg, #ffffff 0%, var(--warm) 100%);
      line-height: 1.7;
      word-break: keep-all;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    a { color: inherit; text-decoration: none; }
    .wrap { width: min(var(--max), calc(100% - 40px)); margin: 0 auto; }

    header {
      position: sticky;
      top: 0;
      z-index: 20;
      background: rgba(255, 255, 255, 0.78);
      backdrop-filter: blur(18px);
      border-bottom: 1px solid rgba(227, 232, 225, 0.75);
    }
    .nav {
      height: 66px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 20px;
    }
    .brand {
      display: inline-flex;
      align-items: center;
      gap: 10px;
      font-family: var(--font-display);
      font-weight: 800;
      color: var(--green-deep);
      letter-spacing: -0.03em;
    }
    .brand-mark {
      width: 34px;
      height: 34px;
      border-radius: 999px;
      display: grid;
      place-items: center;
      color: white;
      background: linear-gradient(135deg, var(--green), var(--green-bright));
      box-shadow: 0 12px 28px rgba(21, 128, 61, 0.22);
    }
    .nav-links { display: flex; align-items: center; gap: 18px; font-size: 14px; color: var(--muted); }
    .nav-links a:hover { color: var(--green); }

    .content-area {
      flex: 1;
      padding: 40px 0 80px;
    }

    .slider-title-area {
      text-align: center;
      margin-bottom: 30px;
    }
    .slider-title-area p {
      margin: 0 0 8px;
      color: var(--green);
      font-weight: 900;
      font-size: 13px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }
    .slider-title-area h1 {
      font-family: var(--font-display);
      margin: 0;
      color: var(--ink);
      font-size: clamp(26px, 4vw, 36px);
      letter-spacing: -0.04em;
    }

    .slider-container {
      background: white;
      border: 1px solid var(--line);
      border-radius: var(--radius-xl);
      box-shadow: var(--shadow);
      overflow: hidden;
      position: relative;
    }

    .progress-bar-container {
      background: var(--surface);
      height: 6px;
      width: 100%;
      border-bottom: 1px solid var(--line);
      position: relative;
    }
    .progress-bar-fill {
      height: 100%;
      background: linear-gradient(90deg, var(--green), var(--green-bright));
      width: 25%;
      transition: width 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    }

    .step-header {
      padding: 24px 40px 0;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .step-number {
      font-family: var(--font-display);
      font-weight: 800;
      color: var(--green);
      font-size: 14px;
      background: var(--green-mist);
      padding: 6px 14px;
      border-radius: 999px;
      border: 1px solid var(--line-green);
    }
    .step-total {
      font-size: 13px;
      color: var(--muted);
      font-weight: 700;
    }

    .slides-wrapper {
      position: relative;
      min-height: 280px;
    }
    .slide-card {
      padding: 20px 40px 40px;
      display: none;
      opacity: 0;
      transition: opacity 0.3s ease;
    }
    .slide-card.active {
      display: block;
      opacity: 1;
      animation: slideIn 0.4s ease;
    }
    @keyframes slideIn {
      from { transform: translateY(8px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }

    .slide-card h2 {
      font-family: var(--font-display);
      margin: 10px 0 14px;
      color: var(--ink);
      font-size: 22px;
      letter-spacing: -0.02em;
    }
    .slide-card p {
      color: var(--muted);
      font-size: 15px;
      line-height: 1.65;
      margin-top: 0;
      margin-bottom: 20px;
    }

    .guide-box {
      background: var(--surface);
      border: 1px solid var(--line);
      border-radius: 14px;
      padding: 18px;
      margin-bottom: 20px;
    }
    .guide-box ol, .guide-box ul {
      margin: 0;
      padding-left: 20px;
      color: #334238;
      font-size: 15px;
    }
    .guide-box li {
      margin-bottom: 8px;
    }
    .guide-box li:last-child {
      margin-bottom: 0;
    }
    
    .tip-box {
      background: #fefcbf;
      border: 1px solid #fef08a;
      color: #713f12;
      border-radius: 10px;
      padding: 12px 16px;
      font-size: 13.5px;
      line-height: 1.5;
      margin-top: 15px;
    }

    .visual-diff-box {
      font-family: monospace;
      background: var(--dark);
      color: #e2e8f0;
      border-radius: 12px;
      padding: 16px;
      font-size: 13.5px;
      line-height: 1.5;
      overflow-x: auto;
      margin-bottom: 15px;
    }
    .diff-line {
      display: block;
      padding: 2px 0;
    }
    .diff-del {
      background-color: rgba(239, 68, 68, 0.2);
      color: #fca5a5;
      border-radius: 4px;
      padding: 0 4px;
      text-decoration: line-through;
    }
    .diff-add {
      background-color: rgba(34, 197, 94, 0.2);
      color: #86efac;
      border-radius: 4px;
      padding: 0 4px;
    }

    .action-btn-area {
      margin: 20px 0 10px;
      text-align: center;
    }
    .btn-action {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      background: var(--green);
      color: white;
      font-weight: 800;
      font-size: 15px;
      padding: 12px 24px;
      border-radius: 999px;
      box-shadow: 0 10px 24px rgba(21, 128, 61, 0.16);
      transition: transform 0.18s ease, background-color 0.18s ease;
      border: none;
      cursor: pointer;
    }
    .btn-action:hover {
      transform: translateY(-1.5px);
      background-color: var(--green-bright);
    }

    .slider-nav {
      border-top: 1px solid var(--line);
      padding: 20px 40px;
      display: flex;
      justify-content: space-between;
      background: var(--surface);
    }
    .btn-nav {
      min-height: 44px;
      padding: 0 20px;
      border-radius: 999px;
      font-weight: 800;
      font-size: 13.5px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      transition: transform 0.18s ease, background 0.18s ease;
      border: 1px solid var(--line);
      background: white;
      color: var(--ink);
    }
    .btn-nav:hover {
      background: var(--surface);
      transform: translateY(-1px);
    }
    .btn-nav.disabled {
      opacity: 0.35;
      cursor: not-allowed;
      pointer-events: none;
    }
    .btn-nav-next {
      background: var(--green-deep);
      color: white;
      border: none;
    }
    .btn-nav-next:hover {
      background: var(--dark);
    }

    footer {
      padding: 40px 0;
      background: var(--dark);
      color: rgba(255,255,255,.78);
      margin-top: auto;
      font-size: 13.5px;
    }
    footer .wrap { display: flex; justify-content: space-between; gap: 24px; align-items: center; flex-wrap: wrap; }
    footer b { color: white; }

    @media (max-width: 640px) {
      .slide-card { padding: 15px 20px 30px; }
      .slider-nav { padding: 16px 20px; }
      .step-header { padding: 20px 20px 0; }
    }

    /* 가이드 스크린샷 이미지 스타일 */
    .guide-img-container {
      display: flex;
      flex-direction: column;
      gap: 20px;
      margin: 24px 0;
    }
    .guide-screenshot-box {
      border: 1px solid var(--line);
      border-radius: 14px;
      overflow: hidden;
      box-shadow: 0 6px 16px rgba(16, 36, 24, 0.05);
      background: white;
    }
    .guide-screenshot-box span {
      display: block;
      padding: 10px 16px;
      background: var(--surface);
      border-bottom: 1px solid var(--line);
      font-size: 13px;
      font-weight: 800;
      color: var(--green-deep);
    }
    .guide-screenshot-img {
      display: block;
      width: 100%;
      height: auto;
    }

    /* 인라인 UI 뱃지 스타일 */
    .badge-ui {
      display: inline-flex;
      align-items: center;
      background: #f1f5f9;
      color: #334155;
      border: 1px solid #cbd5e1;
      padding: 2px 6px;
      font-size: 13px;
      font-weight: 700;
      border-radius: 6px;
      font-family: var(--font-body);
      vertical-align: middle;
      line-height: 1.2;
      margin: 0 2px;
    }
    .badge-action {
      display: inline-flex;
      align-items: center;
      background: var(--green);
      color: white;
      padding: 2px 8px;
      font-size: 13px;
      font-weight: 700;
      border-radius: 6px;
      font-family: var(--font-body);
      vertical-align: middle;
      line-height: 1.2;
      margin: 0 2px;
    }
    .badge-action.blue {
      background: #0284c7;
    }

    /* 1:1 이미지-텍스트 흐름 레이아웃 */
    .flow-container {
      display: flex;
      flex-direction: column;
      gap: 24px;
      margin: 20px 0;
    }
    .flow-item {
      background: var(--surface);
      border: 1px solid var(--line);
      border-radius: 16px;
      overflow: hidden;
      box-shadow: 0 4px 12px rgba(16, 36, 24, 0.03);
      display: flex;
      flex-direction: column;
    }
    .flow-text {
      padding: 18px 20px;
      border-bottom: 1px solid var(--line);
    }
    .flow-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 8px;
    }
    .flow-num {
      background: var(--green-soft);
      color: var(--green-deep);
      font-weight: 800;
      font-size: 12px;
      padding: 2px 8px;
      border-radius: 999px;
      font-family: var(--font-display);
    }
    .flow-title {
      font-family: var(--font-display);
      font-weight: 800;
      font-size: 15.5px;
      color: var(--ink);
    }
    .flow-desc {
      margin: 0;
      font-size: 14.5px;
      color: var(--body);
      line-height: 1.6;
    }
    .flow-media {
      background: white;
      padding: 12px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .flow-screenshot {
      display: block;
      width: 100%;
      max-width: 100%;
      height: auto;
      border-radius: 8px;
      border: 1px solid #f1f5f9;
      box-shadow: 0 2px 8px rgba(0,0,0,0.02);
    }

    /* 아코디언 스타일 (details / summary) */
    .accordion-tip {
      background: var(--warm);
      border: 1px solid var(--line);
      border-radius: 12px;
      margin-bottom: 16px;
      overflow: hidden;
      transition: all 0.2s ease;
    }
    .accordion-tip[open] {
      box-shadow: 0 8px 20px rgba(0, 0, 0, 0.03);
      border-color: var(--line-green);
    }
    .accordion-tip summary {
      padding: 16px 20px;
      font-weight: 800;
      font-size: 14.5px;
      color: var(--green-deep);
      cursor: pointer;
      user-select: none;
      display: flex;
      align-items: center;
      justify-content: space-between;
      outline: none;
      font-family: var(--font-display);
    }
    .accordion-tip summary::-webkit-details-marker {
      display: none;
    }
    .accordion-tip summary::after {
      content: "▼";
      font-size: 10px;
      color: var(--green);
      transition: transform 0.2s ease;
    }
    .accordion-tip[open] summary::after {
      transform: rotate(180deg);
    }
    .accordion-content {
      padding: 0 20px 20px;
      font-size: 13.5px;
      color: var(--body);
      line-height: 1.65;
      border-top: 1px dashed var(--line);
      padding-top: 16px;
    }
    .accordion-content ul, .accordion-content ol {
      margin: 0;
      padding-left: 20px;
    }
    .accordion-content li {
      margin-bottom: 6px;
    }
    .accordion-content li:last-child {
      margin-bottom: 0;
    }
  </style>
</head>
<body>
  <header>
    <div class="wrap nav">
      <a href="../index.html" class="brand" aria-label="초록덕후의 교실 도구함 홈">
        <span class="brand-mark">&#127807;</span>
        <span>초록덕후의 교실 도구함</span>
      </a>
      <nav class="nav-links" aria-label="주요 메뉴">
        <a href="../index.html">홈으로</a>
      </nav>
    </div>
  </header>

  <main class="content-area">
    <div class="wrap">
      
      <div class="slider-title-area">
        <p>Vibe Coding</p>
        <h1>동학년 게시판 만들기</h1>
        <p style="font-size: 16px; color: var(--muted); margin: 10px 0 0;">기 완성된 동학년 협업 템플릿에 실시간 서버를 붙이고 나만의 디자인으로 수정해봅니다.</p>
      </div>

      <div class="slider-container">
        <!-- 상단 프로그레스 바 -->
        <div class="progress-bar-container">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>

        <!-- 상단 라벨 -->
        <div class="step-header">
          <div class="step-number" id="stepNumber">1단계</div>
          <div class="step-total" id="stepTotal">1 / 4 단계</div>
        </div>

        <!-- 슬라이드 카드 모음 -->
        <div class="slides-wrapper">
          
          <!-- [1단계] -->
          <div class="slide-card active" data-step="1">
            <h2>1단계: 동학년 게시판 둘러보고 복제하기 (Remix)</h2>
            <p>동학년 협업 게시판의 주요 기능들을 살펴보고 내 보관함에 복제합니다.</p>

            <div class="flow-container">
              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">기능 1</span>
                    <span class="flow-title">공지사항 게시판</span>
                  </div>
                  <p class="flow-desc">동학년 중요한 긴급 공지를 실시간으로 등록하고 한눈에 함께 확인합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-preview-notice.png" alt="동학년 게시판 공지사항 미리보기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">기능 2</span>
                    <span class="flow-title">학년 달력 공유 (일정 추가)</span>
                  </div>
                  <p class="flow-desc">학년 공동 행사, 수행평가 일정, 현장체험 등 학년 스케줄을 캘린더로 공동 관리합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-preview-calendar.png" alt="동학년 게시판 학년달력 미리보기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">기능 3</span>
                    <span class="flow-title">의견 수렴 (투표하기)</span>
                  </div>
                  <p class="flow-desc">의결이 필요하거나 빠른 의견 취합이 필요할 때 간편히 무기명/기명 투표를 개설합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-preview-vote.png" alt="동학년 게시판 의견수렴 미리보기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">기능 4</span>
                    <span class="flow-title">기자재 및 특별실 예약</span>
                  </div>
                  <p class="flow-desc">학년 공용 교구나 컴퓨터실 사용 일정이 겹치지 않게 실시간 예약 현황을 관리합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-preview-reserve.png" alt="동학년 게시판 기자재예약 미리보기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">기능 5</span>
                    <span class="flow-title">데이터 통합 관리자 페이지</span>
                  </div>
                  <p class="flow-desc">상단 메뉴의 [관리자] 탭에서 동학년 게시판의 모든 등록 데이터를 직접 삭제 및 관리(초기화)할 수 있습니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-preview-admin.png" alt="동학년 게시판 관리자 모드 미리보기" />
                </div>
              </div>
            </div>

            <!-- 관리자 모드 안내 & 교육망 차단 안내 아코디언 -->
            <details class="accordion-tip" style="margin-top: 20px;">
              <summary>🛡️ 데이터 삭제를 위한 관리자 비밀번호가 무엇인가요?</summary>
              <div class="accordion-content">
                초기 관리자 비밀번호는 <b><code>0000</code></b>으로 세팅되어 있습니다. 관리자 페이지 진입 시 비밀번호를 입력하면 등록된 모든 공지, 일정, 투표, 예약을 관리할 수 있습니다.
              </div>
            </details>

            <details class="accordion-tip">
              <summary>⚠️ 중요: 학교/교육청 계정 접속 차단 대처 방법</summary>
              <div class="accordion-content">
                학교/교육청 구글 계정(예: <code>@o365.go.kr</code>, <code>@office.edu</code> 등)은 교육망 보안 및 연령 제한 정책에 의해 AI Studio 서비스 접근이 차단됩니다. <b>반드시 개인 구글 계정(@gmail.com)</b>으로 크롬 브라우저에 로그인하신 후 실습해 주세요.
              </div>
            </details>

            <div class="flow-item" style="margin-top: 24px;">
              <div class="flow-text" style="border-bottom: none;">
                <div class="flow-header">
                  <span class="flow-num">복제 준비</span>
                  <span class="flow-title">동학년 게시판 복제 준비 완료하기</span>
                </div>
                <p class="flow-desc">개인 구글 계정 로그인을 확인하셨다면 아래 <b>[동학년 게시판 템플릿 복제하기 🌿]</b> 버튼을 클릭하여 공유된 AI Studio 템플릿 페이지를 엽니다.</p>
              </div>
            </div>

            <div class="action-btn-area">
              <a href="https://ai.studio/apps/dcd00c82-5d1d-494c-912f-bea1368a4ddc" target="_blank" rel="noopener" class="btn-action">
                동학년 게시판 템플릿 복제하기 🌿
              </a>
            </div>
          </div>

          <!-- [2단계] -->
          <div class="slide-card" data-step="2">
            <h2>2단계: 게시판 복제 및 실시간 공유 서버 연결하기</h2>
            <p>제공된 템플릿의 사본을 내 계정으로 가져온 뒤, 동학년 선생님들과 데이터를 실시간 공유할 수 있게 서버(데이터베이스)를 연동합니다.</p>

            <details class="accordion-tip">
              <summary>💳 서버 및 배포 요금 걱정 없이 안심하고 사용하기 (필독)</summary>
              <div class="accordion-content">
                <ul>
                  <li><strong>데이터베이스 평생 무료:</strong> 본 실습에서 연동할 파이어베이스(Firebase) 데이터베이스는 무료 등급(Spark 요금제) 한도 내에서 작동하여 요금이 발생하지 않습니다.</li>
                  <li><strong>배포 시 카드 등록 안내:</strong> 마지막 4단계 배포(Publish) 과정에서 구글 클라우드 플랫폼(GCP) 계정 인증 및 본인 확인을 위해 카드 등록 절차가 요구됩니다.</li>
                  <li><strong>텍스트 위주 운영으로 요금 걱정 제로:</strong> 이 게시판은 고용량 사진/영상이 아닌 <b>텍스트 위주의 데이터(공지사항, 달력, 예약 등)만 주고받기 때문에 데이터 소모량이 극히 적습니다.</b> 동학년 선생님들이 일상적인 업무 협업용으로 사용하시는 범위 내에서는 구글이 매월 제공하는 <b>무료 제공량을 초과할 일이 거의 없으므로 청구 요금 걱정 없이 안심하고 사용</b>하셔도 좋습니다!</li>
                </ul>
              </div>
            </details>

            <div class="flow-container">
              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">2-1</span>
                    <span class="flow-title">템플릿 사본 내 보관함에 가져오기</span>
                  </div>
                  <p class="flow-desc">1단계 버튼으로 열린 화면 우측 상단의 <span class="badge-ui">Remix</span> 버튼을 누른 후, 팝업 우측 하단의 <span class="badge-action">Apply</span>를 선택합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step2-remix.png" alt="AI Studio 우측 상단 Remix 버튼 클릭하기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">2-2</span>
                    <span class="flow-title">구글 클라우드 권한 연동하기</span>
                  </div>
                  <p class="flow-desc">화면에 <code>Remix: Set up OAuth</code> 팝업창이 나타나면, 우측 하단의 <span class="badge-action">Let's do it</span> 버튼을 클릭하여 구글 클라우드 권한을 연동합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step2-oauth.png" alt="Remix Set up OAuth 창에서 Let's do it 버튼 클릭하기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">2-3</span>
                    <span class="flow-title">자동 연동 명령어 입력하기</span>
                  </div>
                  <p class="flow-desc">
                    리믹스가 완료되어 편집 화면이 나타나면, 화면 우측 안내 카드의 2번 영역에 있는 <strong>[클릭으로 즉시 복사]</strong> 버튼을 누른 후,
                    좌측 하단의 <strong>채팅창(Prompt Chat)</strong>에 붙여넣고 전송(엔터)합니다.<br>
                    (명령어: <code>파이어베이스 세팅하고 프로젝트 파일 바탕으로 보안규칙도 즉시 배포해줘!</code>)
                  </p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step2-setup.png" alt="파이어베이스 세팅하고 프로젝트 파일 바탕으로 보안규칙도 즉시 배포해줘! 지시어 입력 화면" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">2-4</span>
                    <span class="flow-title">서버 연동 완료 확인</span>
                  </div>
                  <p class="flow-desc">AI 에이전트가 연동 작업을 마치고 화면 중앙의 디자인이 <b>성함을 입력하는 로그인 첫 화면</b>으로 바뀌면 실시간 서버 연동에 성공한 것입니다!</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step2-complete.png" alt="Firebase 연동 완료 후 로그인 화면 전환 모습" />
                </div>
              </div>
            </div>
          </div>

          <!-- [3단계] -->
          <div class="slide-card" data-step="3">
            <h2>3단계: 나만의 게시판으로 맞춤 수정하기 (바이브코딩 체험)</h2>
            <p>서버 연동이 완료된 게시판에 로그인하여 진입한 뒤, 한글 채팅으로 원하는 새로운 기능이나 메뉴 수정을 가볍게 지시해 봅니다.</p>

            <details class="accordion-tip">
              <summary>🛠️ 바이브코딩 오류 시 자가 복구 팁 (동작이 이상해졌을 때)</summary>
              <div class="accordion-content">
                <ul>
                  <li><strong>원격 되돌리기(Undo)</strong>: AI 채팅 답변 도중 기존 로직이 깨지거나 오작동하면, 당황하지 말고 우측 채팅창에서 <b>이전 질문/답변 블록을 삭제(또는 실행 취소/Undo)</b>하여 직전 성공 시점으로 되돌리세요.</li>
                  <li><strong>점진적 명령</strong>: 한 번에 너무 많은 기능 수정을 요구하면 코드가 망가지기 쉽습니다. 기능 한 개씩 자유롭게 바이브코딩하며 매번 작동을 점검하세요.</li>
                </ul>
              </div>
            </details>

            <div class="flow-container">
              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">3-1</span>
                    <span class="flow-title">이름 입력하고 소통 시작하기</span>
                  </div>
                  <p class="flow-desc">성함을 입력한 후 <span class="badge-action">동학년 소통 시작하기</span>를 누르면 게시판 실물 화면으로 입장합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step3-login.png" alt="동학년 게시판 성함 입력 화면" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">3-2</span>
                    <span class="flow-title">한글 채팅으로 맞춤 기능 추가하기</span>
                  </div>
                  <p class="flow-desc">좌측 하단의 <b>채팅창(Prompt Chat)</b>에 원하는 기능 추가 및 텍스트/디자인 수정을 요청해 봅니다.</p>
                  <div class="visual-diff-box" style="font-family: monospace; background: var(--dark); color: #86efac; padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 13px;">
                    💬 "동학년 선생님들과 공유할 수 있는 메모장 메뉴를 만들어줘" (추천 예시)<br>
                    💬 "상단 타이틀 문구를 '2026학년도 5학년 동학년 게시판 🌿'으로 수정해줘."<br>
                    💬 "메뉴 탭 중에서 [기타 자료] 이름을 [행정 업무]로 변경해줘."
                  </div>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step3-customize.png" alt="바이브코딩으로 메모장 추가 요청하는 화면" />
                </div>
              </div>
            </div>
          </div>

          <!-- [4단계] -->
          <div class="slide-card" data-step="4">
            <h2>4단계: 배포하고 바탕화면 설치 & 동학년 공유하기</h2>
            <p>나만의 주소로 게시판을 업로드하여 동학년 선생님들과 고유 주소를 공유하고협업을 시작합니다.</p>

            <div class="tip-box" style="background: var(--green-mist); border: 1px solid var(--line-green); color: var(--green-deep); margin-bottom: 20px;">
              💡 <b>안내:</b> 마지막 4단계(배포 및 바탕화면 PWA 앱 설치)는 앞서 진행한 <b>학급일지 배포하기 강좌와 모든 순서와 과정이 동일</b>합니다. 학급일지를 이미 배포해 보셨다면 더욱 쉽고 막힘없이 진행하실 수 있습니다!
            </div>

            <details class="accordion-tip">
              <summary>💳 구글 클라우드 배포 및 결제 등록 정보 (필독)</summary>
              <div class="accordion-content">
                <ul>
                  <li><strong>최초 1회만 연동:</strong> 결제 계정 카드 등록은 최초 1회만 해두면 향후 다른 AI 앱 배포 시 번거로운 과정 없이 편리하게 사용할 수 있습니다.</li>
                  <li><strong>무료 요금 범위 안내:</strong> Gemini 1.5 Flash 기준 <b>15 RPM / 1,500 RPD</b>의 무료 제공량이 기본 적용되므로 개인/동학년 협업 수준에서는 과금될 일이 전혀 없으니 안심하셔도 됩니다.</li>
                  <li><strong>카드 등록을 하지 않고 사용하는 법 (우회책):</strong> 신용카드 등록이 곤란한 경우 배포(Publish)하지 않고 AI Studio 우측의 <b>[Preview]</b> 화면을 전체화면으로 넓혀서 실습하고 즉석에서 소통 공간으로 활용하셔도 무방합니다.</li>
                </ul>
              </div>
            </details>

            <details class="accordion-tip">
              <summary>🌿 번거로운 매번 로그인 방지 및 PWA 바로가기 팁</summary>
              <div class="accordion-content">
                <ul>
                  <li><strong>성함 정보 자동 유지:</strong> 입력하신 이름은 브라우저 저장소(IndexedDB)에 자동 보관되어 컴퓨터 포맷 등을 하지 않는 한, **바탕화면 아이콘을 통해 재접속 시 성함 재입력 없이 바로 자동 로그인 진입**합니다.</li>
                  <li><strong>다운로드 아이콘이 안 보일 때 우회 설치:</strong> 크롬 주소창에 다운로드(PWA) 아이콘이 안 보이면 크롬 우측 상단 **[점 3개 메뉴(⋮)] -> [저장 및 공유] -> [바로가기 만들기]**를 클릭하신 뒤, **[창으로 열기] 옵션을 체크**하고 만드시면 됩니다.</li>
                </ul>
              </div>
            </details>

            <div class="flow-container">
              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-1</span>
                    <span class="flow-title">배포 메뉴 진입하기</span>
                  </div>
                  <p class="flow-desc">AI Studio 우측 상단의 <span class="badge-action blue">Publish</span>를 클릭한 뒤, 이어서 나타나는 팝업에서 <span class="badge-action">Get started</span>를 누릅니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-publish.png" alt="AI Studio 우측 상단 Publish 버튼 위치" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-2</span>
                    <span class="flow-title">구글 클라우드 연동</span>
                  </div>
                  <p class="flow-desc">프로젝트 확인 창에서 기본값인 <strong>Default Gemini Project</strong>를 그대로 두고 <span class="badge-action">Set up billing</span>을 클릭합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-project.png" alt="기본 Default Gemini Project 선택 및 Set up billing 버튼 누르기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-3</span>
                    <span class="flow-title">결제 계정 및 본인 인증</span>
                  </div>
                  <p class="flow-desc">화면 안내에 따라 본인 정보 및 결제 수단(신용카드) 연동을 마칩니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-billing.png" alt="고객정보 및 결제 계정 세부정보 추가 화면" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-4</span>
                    <span class="flow-title">최종 배포 완료 및 접속</span>
                  </div>
                  <p class="flow-desc">배포가 성공적으로 완료되면 창 상단의 <span class="badge-action">Visit</span> 버튼을 눌러 나만의 실시간 동학년 게시판 고유 링크로 접속합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-complete.png" alt="배포 완료 화면 및 Visit 버튼 확인" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-5</span>
                    <span class="flow-title">PC 바탕화면에 앱으로 다운로드</span>
                  </div>
                  <p class="flow-desc">접속한 브라우저 주소창 우측의 <b>[앱 설치(다운로드)]</b> 아이콘을 클릭하여 PC 바탕화면에 단독 앱 형태로 설치합니다.</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-install.png" alt="주소창 우측 앱 설치 아이콘 클릭하여 바탕화면에 추가하기" />
                </div>
              </div>

              <div class="flow-item">
                <div class="flow-text">
                  <div class="flow-header">
                    <span class="flow-num">4-6</span>
                    <span class="flow-title">바탕화면 아이콘 확인</span>
                  </div>
                  <p class="flow-desc">바탕화면에 생성된 예쁜 <b>[동학년 게시판]</b> 아이콘을 확인합니다. 이제 매번 번거롭게 인터넷 브라우저를 켜지 않고 이 아이콘 더블클릭만으로 즉시 메인 게시판으로 자동 진입합니다!</p>
                </div>
                <div class="flow-media">
                  <img class="flow-screenshot" src="../assets/images/guide-gradeboard-step4-icon.png" alt="바탕화면에 생성된 PWA 바로가기 아이콘" />
                </div>
              </div>
            </div>

            <div class="flow-item" style="margin-top: 24px;">
              <div class="flow-text" style="border-bottom: none;">
                <div class="flow-header">
                  <span class="flow-num">협업 시작</span>
                  <span class="flow-title">동학년 공유 및 실시간 소통 개시</span>
                </div>
                <p class="flow-desc">완성된 나만의 사이트 주소(App URL)를 복사하여 <b>동학년 단톡방이나 메신저로 선생님들께 공유</b>하고, 실시간 소통과 업무 조율을 시작해보세요! 🎉</p>
              </div>
            </div>

            <div class="action-btn-area">
              <a href="../index.html" class="btn-action">
                완료하고 홈으로 가기 &#127881;
              </a>
            </div>
          </div>
        </div>

        <!-- 하단 내비게이션 버튼 바 -->
        <div class="slider-nav">
          <button class="btn-nav btn-nav-prev disabled" id="btnPrev">이전 단계</button>
          <button class="btn-nav btn-nav-next" id="btnNext">다음 단계</button>
        </div>

      </div>

    </div>
  </main>

  <footer>
    <div class="wrap">
      <div>선생님들의 편안한 학교생활을 응원합니다</div>
      <div>© 초록덕후의 교실 도구함</div>
    </div>
  </footer>

  <script>
    let currentStep = 1;
    const totalSteps = 4;

    const progressBar = document.getElementById('progressBar');
    const stepNumber = document.getElementById('stepNumber');
    const stepTotal = document.getElementById('stepTotal');
    const btnPrev = document.getElementById('btnPrev');
    const btnNext = document.getElementById('btnNext');

    function changeSlide(direction) {
      const nextStep = currentStep + direction;
      
      if (nextStep < 1 || nextStep > totalSteps) return;

      const activeCard = document.querySelector(`.slide-card[data-step="${currentStep}"]`);
      activeCard.classList.remove('active');

      currentStep = nextStep;
      const nextCard = document.querySelector(`.slide-card[data-step="${currentStep}"]`);
      nextCard.classList.add('active');

      updateUI();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    function updateUI() {
      const percentage = (currentStep / totalSteps) * 100;
      progressBar.style.width = percentage + '%';

      stepNumber.textContent = currentStep + '단계';
      stepTotal.textContent = currentStep + ' / ' + totalSteps + ' 단계';

      if (currentStep === 1) {
        btnPrev.classList.add('disabled');
      } else {
        btnPrev.classList.remove('disabled');
      }

      if (currentStep === totalSteps) {
        btnNext.textContent = '처음으로 돌아가기';
      } else {
        btnNext.textContent = '다음 단계';
      }
    }

    btnNext.addEventListener('click', function() {
      if (currentStep === totalSteps) {
        const activeCard = document.querySelector(`.slide-card[data-step="${currentStep}"]`);
        activeCard.classList.remove('active');
        
        currentStep = 1;
        const firstCard = document.querySelector(`.slide-card[data-step="1"]`);
        firstCard.classList.add('active');
        updateUI();
        window.scrollTo({ top: 0, behavior: 'smooth' });
      } else {
        changeSlide(1);
      }
    });

    btnPrev.addEventListener('click', function() {
      changeSlide(-1);
    });
  </script>
</body>
</html>
"""

with open("guides/vibe-coding-grade-board.html", "w", encoding="utf-8") as out:
    out.write(html_content)

print("HTML write success!")
